import { useMemo, useState, type FormEvent } from 'react';
import { FolderPlus, Layers3, Search, Shirt, SlidersHorizontal, X } from 'lucide-react';
import { Badge } from '../../components/shared/Badge';
import { Button } from '../../components/shared/Button';
import { CanonicalMediaImage } from '../../components/shared/CanonicalMediaImage';
import { CanonicalWorkspaceState } from '../../components/shared/CanonicalWorkspaceState';
import { Card } from '../../components/shared/Card';
import { PageHeader } from '../../components/shared/PageHeader';
import type { CanonicalGarment, CanonicalWorkspaceState as WorkspaceState } from '../../domains/workspace';
import { useCanonicalWorkspace } from '../../hooks/useCanonicalWorkspace';
import { canonicalGarmentCover, canonicalGarmentSwatches, recentCanonicalGarments } from '../../lib/canonicalGarmentPresentation';

type LibraryFilters = { collectionId: string | 'all'; phase: CanonicalGarment['phase'] | 'all'; status: CanonicalGarment['status'] | 'all' };
const initialFilters: LibraryFilters = { collectionId: 'all', phase: 'all', status: 'all' };

export function GarmentLibraryPage({ onOpenGarment }: { onOpenGarment: (id: string) => void }) {
  const { addCollection, addGarment, state } = useCanonicalWorkspace();
  const [query, setQuery] = useState('');
  const [filters, setFilters] = useState<LibraryFilters>(initialFilters);
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [addingGarment, setAddingGarment] = useState(false);
  const [addingCollection, setAddingCollection] = useState(false);
  const activeFilterCount = Object.values(filters).filter((value) => value !== 'all').length;
  const garments = useMemo(() => {
    if (!state) return [];
    const collections = new Map(state.collections.map((collection) => [collection.id, collection.name]));
    const needle = query.trim().toLowerCase();
    return recentCanonicalGarments(state.garments).filter((garment) => {
      const text = `${garment.title} ${garment.garmentCode} ${garment.garmentType} ${collections.get(garment.collectionId ?? '') ?? ''}`.toLowerCase();
      return (!needle || text.includes(needle)) && (filters.collectionId === 'all' || garment.collectionId === filters.collectionId) && (filters.phase === 'all' || garment.phase === filters.phase) && (filters.status === 'all' || garment.status === filters.status);
    });
  }, [filters, query, state]);

  const createGarment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const title = String(form.get('title') ?? '').trim(); if (!title) return; const id = addGarment({ collectionId: String(form.get('collectionId') || '') || null, garmentType: String(form.get('garmentType') || 'Other'), phase: 'brief', status: 'draft', title }); setAddingGarment(false); onOpenGarment(id); };
  const createCollection = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get('name') ?? '').trim(); if (!name) return; const id = addCollection(name, String(form.get('season') ?? '')); setFilters((current) => ({ ...current, collectionId: id })); setAddingCollection(false); };

  return <CanonicalWorkspaceState><section className="space-y-7 lg:space-y-9">
    <PageHeader badge="Garments" description="Browse the collection by silhouette, material, and momentum. Open a piece when you are ready to continue its story." title="Garment Library"><div className="flex flex-wrap gap-2"><Button icon={<Layers3 aria-hidden="true" size={16} />} onClick={() => setAddingCollection((value) => !value)} size="sm" variant="ghost">New collection</Button><Button icon={<FolderPlus aria-hidden="true" size={16} />} onClick={() => setAddingGarment((value) => !value)} size="sm" variant="primary">New garment</Button></div></PageHeader>
    {addingCollection ? <Card><form className="grid gap-3 sm:grid-cols-[1fr_12rem_auto]" onSubmit={createCollection}><label><span className="sr-only">Collection name</span><input autoFocus className="field" name="name" placeholder="Collection name" required /></label><label><span className="sr-only">Season</span><input className="field" name="season" placeholder="Season / year" /></label><Button type="submit" variant="primary">Create collection</Button></form></Card> : null}
    {addingGarment ? <Card><form className="grid gap-3 md:grid-cols-[1.2fr_0.8fr_0.8fr_auto]" onSubmit={createGarment}><label><span className="sr-only">Garment title</span><input autoFocus className="field" name="title" placeholder="Garment title" required /></label><label><span className="sr-only">Garment type</span><input className="field" defaultValue="Jacket" name="garmentType" /></label><label><span className="sr-only">Collection</span><select className="field" defaultValue="" name="collectionId"><option value="">No collection</option>{state?.collections.map((collection) => <option key={collection.id} value={collection.id}>{collection.name}</option>)}</select></label><Button type="submit" variant="primary">Create garment</Button></form></Card> : null}

    <div className="space-y-3"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search garments</span><Search aria-hidden="true" className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-stardust/38" size={18}/><input className="field min-h-12 bg-stardust/[0.025] pl-11" onChange={(event) => setQuery(event.target.value)} placeholder="Search garments or collections" type="search" value={query}/></label><Button aria-expanded={filtersOpen} className="shrink-0" icon={<SlidersHorizontal aria-hidden="true" size={17} />} onClick={() => setFiltersOpen((value) => !value)} variant={filtersOpen ? 'secondary' : 'ghost'}>Filters{activeFilterCount ? ` · ${activeFilterCount}` : ''}</Button></div>{filtersOpen ? <FilterPanel filters={filters} onChange={setFilters} onClear={() => setFilters(initialFilters)} state={state} /> : null}<div className="flex items-center justify-between gap-4 text-xs text-stardust/42"><p aria-live="polite">{garments.length} garment{garments.length === 1 ? '' : 's'}</p>{(query || activeFilterCount) ? <button className="inline-flex min-h-10 items-center gap-1.5 rounded-lg px-2 text-stardust/58 hover:bg-stardust/[0.05] hover:text-stardust" onClick={() => { setQuery(''); setFilters(initialFilters); }} type="button"><X aria-hidden="true" size={14} />Clear view</button> : null}</div></div>
    {filters.collectionId !== 'all' ? <CollectionIntro collectionId={filters.collectionId} state={state} /> : null}
    {garments.length && state ? <div className="grid gap-x-4 gap-y-7 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4" data-testid="garment-grid">{garments.map((garment) => <GarmentCard garment={garment} key={garment.id} onContinue={() => onOpenGarment(garment.id)} state={state} />)}</div> : <LibraryEmpty filtered={Boolean(query || activeFilterCount)} onCreate={() => setAddingGarment(true)} onReset={() => { setQuery(''); setFilters(initialFilters); }} />}
  </section></CanonicalWorkspaceState>;
}

function GarmentCard({ garment, onContinue, state }: { garment: CanonicalGarment; onContinue: () => void; state: WorkspaceState }) { const collection = state.collections.find((item) => item.id === garment.collectionId); const cover = canonicalGarmentCover(state, garment.id); const swatches = canonicalGarmentSwatches(state, garment.id); return <article className="group min-w-0 overflow-hidden rounded-[1.3rem] bg-stardust/[0.025] shadow-[0_14px_38px_rgba(0,0,0,0.12)] transition duration-300 hover:-translate-y-1 hover:bg-stardust/[0.045] hover:shadow-[0_22px_56px_rgba(0,0,0,0.22)]" data-testid="garment-card"><div className="relative aspect-[4/5] overflow-hidden"><CanonicalMediaImage alt={`${garment.title} garment`} asset={cover} className="h-full w-full rounded-b-none border-0 transition duration-500 group-hover:scale-[1.015]" derivatives={state.mediaDerivatives} fit="cover" mode="library" /><div className="pointer-events-none absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-midnight/72 to-transparent" /><div className="absolute bottom-4 left-4"><PhasePill phase={garment.phase} /></div>{garment.status === 'on_hold' ? <Badge className="absolute right-4 top-4" variant="ember">On hold</Badge> : null}</div><div className="p-4 sm:p-5"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><h2 className="font-display min-h-[3.25rem] break-words text-2xl leading-[1.08] text-stardust">{garment.title}</h2><p className="mt-1 truncate text-sm text-stardust/48">{collection?.name ?? 'Independent piece'} · {garment.garmentType}</p></div><MaterialSwatches swatches={swatches} /></div><Button className="mt-5 w-full" onClick={onContinue} size="sm" variant="primary">Continue</Button></div></article>; }
function FilterPanel({ filters, onChange, onClear, state }: { filters: LibraryFilters; onChange: (filters: LibraryFilters) => void; onClear: () => void; state: WorkspaceState | null }) { return <div className="grid gap-3 rounded-2xl bg-stardust/[0.025] p-4 sm:grid-cols-3 lg:grid-cols-[1fr_1fr_1fr_auto]" role="group" aria-label="Garment filters"><label><span className="mb-2 block text-[0.65rem] uppercase tracking-[0.15em] text-stardust/42">Collection</span><select className="field" onChange={(event) => onChange({ ...filters, collectionId: event.target.value })} value={filters.collectionId}><option value="all">All collections</option>{state?.collections.map((collection) => <option key={collection.id} value={collection.id}>{collection.name}</option>)}</select></label><label><span className="mb-2 block text-[0.65rem] uppercase tracking-[0.15em] text-stardust/42">Phase</span><select className="field" onChange={(event) => onChange({ ...filters, phase: event.target.value as LibraryFilters['phase'] })} value={filters.phase}><option value="all">Every phase</option>{['brief', 'design', 'materials', 'technical', 'sampling', 'production', 'story', 'portfolio'].map((phase) => <option key={phase} value={phase}>{humanize(phase)}</option>)}</select></label><label><span className="mb-2 block text-[0.65rem] uppercase tracking-[0.15em] text-stardust/42">Status</span><select className="field" onChange={(event) => onChange({ ...filters, status: event.target.value as LibraryFilters['status'] })} value={filters.status}><option value="all">Every status</option>{['draft', 'active', 'on_hold', 'approved', 'released', 'archived', 'cancelled'].map((status) => <option key={status} value={status}>{humanize(status)}</option>)}</select></label><Button className="self-end" onClick={onClear} variant="ghost">Reset</Button></div>; }
function CollectionIntro({ collectionId, state }: { collectionId: string; state: WorkspaceState | null }) { const collection = state?.collections.find((item) => item.id === collectionId); if (!collection) return null; const count = state?.garments.filter((item) => item.collectionId === collectionId).length ?? 0; return <div className="flex flex-wrap items-end justify-between gap-4 border-y border-bronze/16 py-5"><div><p className="text-[0.65rem] uppercase tracking-[0.18em] text-ember/70">Collection</p><h2 className="font-display mt-2 text-3xl text-stardust">{collection.name}</h2><p className="mt-1 text-sm text-stardust/44">{collection.season || 'Open season'}</p></div><p className="text-sm text-stardust/46">{count} garment{count === 1 ? '' : 's'}</p></div>; }
function LibraryEmpty({ filtered, onCreate, onReset }: { filtered: boolean; onCreate: () => void; onReset: () => void }) { return <div className="atelier-empty-state flex min-h-[24rem] flex-col items-center justify-center"><Shirt aria-hidden="true" className="text-ember/58" size={38}/><h2 className="font-display mt-5 text-3xl text-stardust">{filtered ? 'No garments in this view' : 'Your garment library begins here'}</h2><p className="mt-3 max-w-lg text-sm leading-6 text-stardust/52">{filtered ? 'Try a wider search or clear the filters to return to the full visual library.' : 'Create a garment, add its first image, and let every material, technical decision, and story gather around it.'}</p><Button className="mt-6" onClick={filtered ? onReset : onCreate} variant="primary">{filtered ? 'Clear filters' : 'Create first garment'}</Button></div>; }
function PhasePill({ phase }: { phase: string }) { return <span className="inline-flex min-h-7 items-center rounded-full bg-midnight/74 px-2.5 text-[0.64rem] font-medium uppercase tracking-[0.13em] text-ember ring-1 ring-bronze/30 backdrop-blur-md">{phase}</span>; }
function MaterialSwatches({ swatches }: { swatches: ReturnType<typeof canonicalGarmentSwatches> }) { return swatches.length ? <div aria-label={`${swatches.length} selected materials`} className="flex shrink-0 -space-x-1">{swatches.map((swatch) => <span aria-label={`${swatch.materialName}, ${swatch.colorName}`} className="h-7 w-7 rounded-full border-2 border-[#11100e] shadow-sm" key={swatch.id} role="img" style={{ background: swatch.colorHex ?? 'linear-gradient(135deg,#9a6c3c,#1b3a63)' }} />)}</div> : null; }
function humanize(value: string) { return value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
