import { ArrowRight, Move, Plus, RotateCcw, Trash2 } from 'lucide-react';
import type { StructuralDiff } from '../../domains/versioning';
import { Badge } from '../shared/Badge';

export function DiffViewer({ diffs, selectedKeys, setSelectedKeys }: { diffs: StructuralDiff[]; selectedKeys: string[]; setSelectedKeys: (keys: string[]) => void }) {
  const toggle = (key: string) => setSelectedKeys(selectedKeys.includes(key) ? selectedKeys.filter((item) => item !== key) : [...selectedKeys, key]);
  if (!diffs.length) return <div className="rounded-2xl border border-dashed border-bronze/28 px-6 py-12 text-center"><p className="font-display text-2xl">No structural differences</p><p className="mt-2 text-sm text-stardust/50">This Freeze Frame matches the comparison state for its selected scope.</p></div>;
  return <div>
    <div className="mb-3 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-stardust/56">{diffs.length} field and row changes · {diffs.filter((item) => item.restorable).length} restorable</p><button className="text-sm text-ember hover:underline" onClick={() => setSelectedKeys(selectedKeys.length ? [] : diffs.filter((item) => item.restorable).map((item) => item.key))} type="button">{selectedKeys.length ? 'Clear selection' : 'Select restorable'}</button></div>
    <div className="hidden overflow-x-auto rounded-2xl border border-bronze/24 md:block"><table className="w-full min-w-[54rem] border-collapse text-left text-sm"><thead className="bg-espresso/55 text-xs uppercase tracking-[0.1em] text-stardust/44"><tr><th className="p-3">Restore</th><th className="p-3">Domain / entity</th><th className="p-3">Field</th><th className="p-3">Before</th><th className="p-3"></th><th className="p-3">After / working</th></tr></thead><tbody>{diffs.map((diff) => <tr className="border-t border-bronze/16 align-top" key={diff.key}><td className="p-3"><input aria-label={`Restore ${diff.entityLabel} ${diff.field}`} checked={selectedKeys.includes(diff.key)} disabled={!diff.restorable} onChange={() => toggle(diff.key)} type="checkbox" /></td><td className="p-3"><Badge variant={domainVariant(diff.domain)}>{diff.domain}</Badge><strong className="mt-2 block">{diff.entityLabel}</strong><span className="text-xs text-stardust/38">{diff.collection}</span></td><td className="p-3 font-mono text-xs">{diff.field}<KindIcon kind={diff.kind} /></td><td className="max-w-64 p-3"><Value value={diff.before} /></td><td className="p-3 text-stardust/35"><ArrowRight size={15} /></td><td className="max-w-64 p-3"><Value value={diff.after} />{diff.warning ? <p className="mt-2 text-xs leading-5 text-ember">{diff.warning}</p> : null}</td></tr>)}</tbody></table></div>
    <div className="min-w-0 space-y-3 md:hidden">{diffs.map((diff) => <article className="min-w-0 rounded-2xl border border-bronze/24 p-4" key={diff.key}><div className="flex min-w-0 items-start gap-3"><input aria-label={`Restore ${diff.entityLabel} ${diff.field}`} checked={selectedKeys.includes(diff.key)} disabled={!diff.restorable} onChange={() => toggle(diff.key)} type="checkbox" /><div className="min-w-0"><Badge variant={domainVariant(diff.domain)}>{diff.domain}</Badge><h3 className="mt-2 break-words font-semibold">{diff.entityLabel}</h3><p className="text-xs text-stardust/42">{diff.field} · {diff.kind}</p></div></div><div className="mt-3 grid min-w-0 gap-2"><Value value={diff.before} /><ArrowRight className="text-stardust/30" size={15} /><Value value={diff.after} /></div>{diff.warning ? <p className="mt-2 text-xs text-ember">{diff.warning}</p> : null}</article>)}</div>
  </div>;
}

function Value({ value }: { value: unknown }) { return <code className="block min-w-0 max-w-full overflow-x-auto break-all whitespace-pre-wrap rounded-lg bg-midnight/55 p-2 text-xs text-stardust/65">{value == null ? '—' : typeof value === 'string' ? value : JSON.stringify(value, null, 2)}</code>; }
function KindIcon({ kind }: { kind: StructuralDiff['kind'] }) { const Icon = kind === 'added' ? Plus : kind === 'removed' ? Trash2 : kind === 'moved' ? Move : RotateCcw; return <Icon aria-label={kind} className="mt-2 text-stardust/38" size={14} />; }
function domainVariant(domain: StructuralDiff['domain']): 'ember' | 'teal' | 'blue' | 'bronze' { return domain === 'technical' ? 'blue' : domain === 'production' ? 'ember' : domain === 'design' ? 'teal' : 'bronze'; }
