import { useMemo, useRef, useState, type ChangeEvent, type FormEvent, type ReactNode } from 'react';
import { Archive, ImagePlus, PackagePlus, Puzzle, Search, Sparkles } from 'lucide-react';
import { Badge } from '../../components/shared/Badge';
import { Button } from '../../components/shared/Button';
import { CanonicalMediaImage } from '../../components/shared/CanonicalMediaImage';
import { CanonicalWorkspaceState } from '../../components/shared/CanonicalWorkspaceState';
import { Card } from '../../components/shared/Card';
import { PageHeader } from '../../components/shared/PageHeader';
import { useCanonicalWorkspace } from '../../hooks/useCanonicalWorkspace';
import { materialAvailableQuantity, type CanonicalMaterialVariant, type CanonicalWorkspaceState as WorkspaceState, type RelationshipOption } from '../../domains/workspace';
import { canonicalGarmentCover } from '../../lib/canonicalGarmentPresentation';

type VaultTab = 'materials' | 'components' | 'templates';

export function LibraryVaultPage() {
  const { addComponent, addMaterial, addTemplate, recordInventory, relationshipOptions, state, uploadGarmentMedia } = useCanonicalWorkspace();
  const [tab, setTab] = useState<VaultTab>('materials');
  const [query, setQuery] = useState('');
  const [createOpen, setCreateOpen] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const contextUploadRef = useRef<HTMLInputElement>(null);
  const contextGarmentRef = useRef<string | null>(null);

  const materialVariants = useMemo(() => {
    if (!state) return [];
    const needle = query.trim().toLowerCase();
    return state.materialVariants.filter((variant) => {
      const material = state.materials.find((item) => item.id === variant.materialId);
      return `${material?.name ?? ''} ${material?.category ?? ''} ${material?.composition ?? ''} ${variant.colorName} ${variant.sku}`.toLowerCase().includes(needle);
    });
  }, [query, state]);
  const genericOptions = (tab === 'templates'
    ? (state?.templates ?? []).map((template) => ({ detail: `${template.templateType} · version ${template.version}`, id: template.id, inUseBy: [], label: template.name, status: template.status }))
    : relationshipOptions('component'))
    .filter((item) => `${item.label} ${item.detail}`.toLowerCase().includes(query.toLowerCase()));

  const create = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get('name') ?? '').trim(); if (!name) return;
    if (tab === 'materials') { const result = addMaterial({ category: String(form.get('category') ?? 'Fabric'), colorHex: String(form.get('colorHex') ?? '') || null, colorName: String(form.get('colorName') ?? '') || 'Natural', composition: String(form.get('composition') ?? ''), name }); setSelectedId(result.variantId); }
    else if (tab === 'components') { const result = addComponent({ category: String(form.get('category') ?? 'Trim'), name }); setSelectedId(result.variantId); }
    else { const id = addTemplate({ name, templateType: String(form.get('templateType') ?? 'bom') as 'pom' | 'measurement' | 'grading' | 'bom' | 'construction' | 'validation' }); setSelectedId(id); }
    setCreateOpen(false);
  };
  const logInventory = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedId) return; const form = new FormData(event.currentTarget); const quantity = Number(form.get('quantity')); if (!Number.isFinite(quantity) || quantity <= 0) return; recordInventory(selectedId, String(form.get('entryType')) as 'receive' | 'reserve' | 'release' | 'consume' | 'return' | 'adjust', quantity, String(form.get('note') ?? '')); };
  const beginContextUpload = (garmentId: string) => { contextGarmentRef.current = garmentId; setNotice(null); contextUploadRef.current?.click(); };
  const uploadContext = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.currentTarget.files?.[0]; event.currentTarget.value = ''; const garmentId = contextGarmentRef.current; if (!file || !garmentId) return; setUploading(true); setNotice(`Preparing ${file.name}…`); try { await uploadGarmentMedia(garmentId, file, 'detail'); setNotice('In-context fabric image added to the garment.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'The image could not be added.'); } finally { setUploading(false); } };
  const selectedVariant = materialVariants.find((item) => item.id === selectedId) ?? materialVariants[0] ?? null;
  const selectedOption = genericOptions.find((item) => item.id === selectedId) ?? genericOptions[0];

  return <CanonicalWorkspaceState><section className="space-y-7 lg:space-y-9">
    <input accept="image/*" className="sr-only" onChange={(event) => void uploadContext(event)} ref={contextUploadRef} type="file" />
    <PageHeader badge="Libraries" description={tab === 'materials' ? 'A tactile archive of fabrics, colors, and the garments they help shape.' : 'Reusable components and technical templates, quietly organized for the workbench.'} title={tab === 'materials' ? 'Material Vault' : tab === 'components' ? 'Component Library' : 'Studio Templates'}><Button icon={tab === 'materials' ? <PackagePlus aria-hidden="true" size={16}/> : <Puzzle aria-hidden="true" size={16}/>} onClick={() => setCreateOpen((value) => !value)} size="sm" variant="primary">New {tab === 'materials' ? 'material' : tab === 'components' ? 'component' : 'template'}</Button></PageHeader>
    <div className="flex flex-col gap-4 border-b border-bronze/16 pb-5 lg:flex-row lg:items-center lg:justify-between"><div className="atelier-tablist"><Tab active={tab === 'materials'} label="Materials" onClick={() => { setTab('materials'); setSelectedId(null); }}/><Tab active={tab === 'components'} label="Components" onClick={() => { setTab('components'); setSelectedId(null); }}/><Tab active={tab === 'templates'} label="Templates" onClick={() => { setTab('templates'); setSelectedId(null); }}/></div><label className="relative w-full lg:max-w-md"><span className="sr-only">Search {tab}</span><Search aria-hidden="true" className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-stardust/38" size={17}/><input className="field min-h-12 bg-stardust/[0.025] pl-11" onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${tab}`} type="search" value={query}/></label></div>
    {createOpen ? <CreateRecordForm onSubmit={create} tab={tab} /> : null}
    {notice ? <p aria-live="polite" className="rounded-xl bg-teal/10 px-4 py-3 text-sm text-teal">{notice}</p> : null}
    {tab === 'materials' ? <MaterialArchive onSelect={setSelectedId} selectedId={selectedVariant?.id ?? null} state={state} variants={materialVariants} /> : <GenericLibrary onSelect={setSelectedId} options={genericOptions} selected={selectedOption} tab={tab} />}
    {tab === 'materials' && selectedVariant && state ? <MaterialDetail beginContextUpload={beginContextUpload} logInventory={logInventory} state={state} uploading={uploading} variant={selectedVariant} /> : null}
  </section></CanonicalWorkspaceState>;
}

function MaterialArchive({ onSelect, selectedId, state, variants }: { onSelect: (id: string) => void; selectedId: string | null; state: WorkspaceState | null; variants: CanonicalMaterialVariant[] }) {
  if (!state || !variants.length) return <MaterialEmpty />;
  return <section aria-labelledby="material-archive-heading"><div className="mb-4 flex items-end justify-between gap-4"><div><p className="text-[0.65rem] uppercase tracking-[0.2em] text-ember/70">Textile archive</p><h2 className="font-display mt-2 text-3xl" id="material-archive-heading">Browse by feel and color</h2></div><p className="text-xs text-stardust/38">{variants.length} material{variants.length === 1 ? '' : 's'}</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{variants.map((variant) => <MaterialCard active={selectedId === variant.id} key={variant.id} onSelect={() => onSelect(variant.id)} state={state} variant={variant} />)}</div></section>;
}

function MaterialCard({ active, onSelect, state, variant }: { active: boolean; onSelect: () => void; state: WorkspaceState; variant: CanonicalMaterialVariant }) {
  const material = state.materials.find((item) => item.id === variant.materialId)!; const garments = garmentsUsingVariant(state, variant.id); const contextAsset = garments.map((garment) => canonicalGarmentCover(state, garment.id)).find(Boolean) ?? null; const available = materialAvailableQuantity(state, variant.id);
  return <button aria-pressed={active} className={active ? 'group overflow-hidden rounded-[1.35rem] bg-stardust/[0.055] text-left ring-1 ring-ember/62' : 'group overflow-hidden rounded-[1.35rem] bg-stardust/[0.025] text-left transition hover:-translate-y-1 hover:bg-stardust/[0.045]'} onClick={onSelect} type="button"><div className="relative aspect-[5/3] overflow-hidden">{contextAsset ? <CanonicalMediaImage alt={`${material.name} used on ${garments[0]?.title}`} asset={contextAsset} className="h-full w-full rounded-b-none border-0 transition duration-500 group-hover:scale-[1.02]" derivatives={state.mediaDerivatives} fit="cover" mode="library" /> : <TextileSwatch className="h-full" color={variant.colorHex} />}<span className="absolute inset-x-0 bottom-0 h-5" style={{ background: swatchBackground(variant.colorHex) }} /></div><div className="p-5"><p className="text-[0.63rem] uppercase tracking-[0.16em] text-ember/70">{material.category}</p><h3 className="font-display mt-2 text-2xl leading-tight text-stardust">{material.name}</h3><p className="mt-2 text-sm text-stardust/48">{variant.colorName || 'Natural'} · {material.composition || 'Composition open'}</p><div className="mt-5 flex items-center justify-between gap-4 text-xs"><span className="text-stardust/42">{garments.length ? `Used in ${garments.length} garment${garments.length === 1 ? '' : 's'}` : 'Awaiting a garment'}</span><span className="text-teal">{available.toFixed(1)} yd</span></div></div></button>;
}

function MaterialDetail({ beginContextUpload, logInventory, state, uploading, variant }: { beginContextUpload: (garmentId: string) => void; logInventory: (event: FormEvent<HTMLFormElement>) => void; state: WorkspaceState; uploading: boolean; variant: CanonicalMaterialVariant }) {
  const material = state.materials.find((item) => item.id === variant.materialId)!; const garments = garmentsUsingVariant(state, variant.id); const suppliers = state.supplierItems.filter((item) => item.materialVariantId === variant.id); const inventory = state.inventoryEntries.filter((item) => item.variantId === variant.id).sort((left, right) => right.occurredAt.localeCompare(left.occurredAt)); const personality = materialPersonality(material.category, material.composition, variant.weightGsm);
  return <section className="space-y-6 border-t border-bronze/16 pt-7" aria-labelledby="material-detail-heading" data-testid="material-story"><div className="grid gap-6 lg:grid-cols-[0.82fr_1.18fr]"><TextileSwatch className="min-h-[22rem]" color={variant.colorHex}><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-midnight/84 to-transparent p-6 pt-20"><p className="text-xs uppercase tracking-[0.18em] text-stardust/54">{variant.colorName || 'Natural'}</p><p className="font-display mt-2 text-3xl text-stardust">{material.name}</p></div></TextileSwatch><div className="flex flex-col justify-center"><p className="text-[0.65rem] uppercase tracking-[0.2em] text-ember/70">Material personality</p><h2 className="font-display mt-3 text-4xl text-stardust" id="material-detail-heading">{personality.title}</h2><p className="mt-4 max-w-2xl text-base leading-7 text-stardust/58">{personality.description}</p><div className="mt-6 flex flex-wrap gap-2"><Pill>{material.category}</Pill><Pill>{material.composition || 'Composition open'}</Pill>{variant.weightGsm ? <Pill>{variant.weightGsm} gsm</Pill> : null}</div></div></div>
    <div><div className="mb-4 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[0.65rem] uppercase tracking-[0.18em] text-ember/70">In the collection</p><h3 className="font-display mt-2 text-3xl">Garments using this fabric</h3></div>{garments[0] ? <Button disabled={uploading} icon={<ImagePlus aria-hidden="true" size={16}/>} onClick={() => beginContextUpload(garments[0].id)} size="sm" variant="ghost">Add in-context image</Button> : null}</div>{garments.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{garments.map((garment) => <article className="overflow-hidden rounded-[1.15rem] bg-stardust/[0.025]" key={garment.id}><CanonicalMediaImage alt={`${material.name} on ${garment.title}`} asset={canonicalGarmentCover(state, garment.id)} className="aspect-[4/3] rounded-b-none border-0" derivatives={state.mediaDerivatives} fit="cover" mode="library" /><div className="p-4"><p className="font-medium text-stardust">{garment.title}</p><p className="mt-1 text-xs text-stardust/42">{garment.phase} · {garment.garmentType}</p></div></article>)}</div> : <div className="atelier-empty-state"><p className="text-sm text-stardust/52">Use this material on a garment to begin seeing it in context.</p></div>}</div>
    <div className="grid gap-4 lg:grid-cols-3"><SecondaryPanel title="Supplier details"><SupplierDetails state={state} supplierItems={suppliers} /></SecondaryPanel><SecondaryPanel title="Inventory"><p className="text-2xl font-semibold tabular-nums text-stardust">{materialAvailableQuantity(state, variant.id).toFixed(2)} <span className="text-sm font-normal text-stardust/42">yd available</span></p><p className="mt-2 text-xs text-stardust/40">{inventory.length} ledger event{inventory.length === 1 ? '' : 's'}</p></SecondaryPanel><SecondaryPanel title="Technical specifications"><dl className="space-y-3"><Info label="SKU" value={variant.sku || 'Open'}/><Info label="Width" value={variant.width ? `${variant.width} ${variant.widthUnit}` : 'Open'}/><Info label="Weight" value={variant.weightGsm ? `${variant.weightGsm} gsm` : 'Open'}/></dl></SecondaryPanel></div>
    <details className="rounded-2xl border border-bronze/16 bg-stardust/[0.018] p-4"><summary className="cursor-pointer text-sm text-stardust/54">Record inventory movement</summary><form className="mt-5 grid gap-3 border-t border-bronze/14 pt-5 md:grid-cols-[10rem_8rem_1fr_auto]" onSubmit={logInventory}><label><span className="field-label">Movement</span><select className="field" defaultValue="receive" name="entryType"><option value="receive">Receive</option><option value="reserve">Reserve</option><option value="release">Release</option><option value="consume">Consume</option><option value="return">Return</option><option value="adjust">Adjust</option></select></label><label><span className="field-label">Quantity (yd)</span><input className="field" min="0.01" name="quantity" step="0.01" type="number" required/></label><label><span className="field-label">Note</span><input className="field" name="note" placeholder="PO, receipt, or adjustment note"/></label><Button className="self-end" type="submit" variant="primary">Record movement</Button></form></details>
  </section>;
}

function GenericLibrary({ onSelect, options, selected, tab }: { onSelect: (id: string) => void; options: RelationshipOption[]; selected: RelationshipOption | undefined; tab: VaultTab }) { return <div className="grid gap-4 xl:grid-cols-[0.8fr_1.2fr]"><Card className="p-3"><p className="px-2 pb-3 text-xs uppercase tracking-[0.12em] text-stardust/45">{options.length} reusable {tab}</p><div className="space-y-2">{options.length ? options.map((item) => <button aria-pressed={selected?.id === item.id} className={selected?.id === item.id ? 'w-full rounded-xl border border-ember/55 bg-ember/10 p-3 text-left' : 'w-full rounded-xl border border-bronze/24 bg-midnight/30 p-3 text-left hover:border-bronze/50'} key={item.id} onClick={() => onSelect(item.id)} type="button"><span className="block text-sm font-medium">{item.label}</span><span className="mt-1 block text-xs text-stardust/55">{item.detail}</span>{item.inUseBy.length ? <span className="mt-2 block text-xs text-teal">Used by {item.inUseBy.join(', ')}</span> : null}</button>) : <Empty tab={tab}/>}</div></Card><Card>{selected ? <GenericDetail option={selected} tab={tab} /> : <Empty tab={tab}/>}</Card></div>; }
function GenericDetail({ option, tab }: { option: RelationshipOption; tab: VaultTab }) { return <><div className="flex flex-wrap justify-between gap-3"><div><Badge variant="blue">{tab === 'components' ? 'Component detail' : 'Template detail'}</Badge><h2 className="font-display mt-3 text-3xl">{option.label}</h2><p className="mt-2 text-sm text-stardust/62">{option.detail}</p></div><Badge variant={option.status === 'archived' ? 'bronze' : 'teal'}>{option.status ?? 'active'}</Badge></div><p className="mt-6 text-sm leading-6 text-stardust/52">{tab === 'templates' ? 'Versioned patterns for repeatable technical work.' : `${option.inUseBy.length ? `Used by ${option.inUseBy.join(', ')}.` : 'Ready to be used in a garment.'}`}</p></>; }
function CreateRecordForm({ onSubmit, tab }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void; tab: VaultTab }) { return <Card><form className="grid gap-3 md:grid-cols-2 xl:grid-cols-5" onSubmit={onSubmit}><label><span className="field-label">Name</span><input autoFocus className="field" name="name" placeholder={`${tab === 'materials' ? 'Material' : tab === 'components' ? 'Component' : 'Template'} name`} required/></label>{tab === 'templates' ? <label><span className="field-label">Template type</span><select className="field" defaultValue="bom" name="templateType"><option value="pom">POM</option><option value="measurement">Measurement</option><option value="grading">Grading</option><option value="bom">BOM</option><option value="construction">Construction</option><option value="validation">Validation</option></select></label> : <label><span className="field-label">Category</span><input className="field" defaultValue={tab === 'materials' ? 'Fabric' : 'Trim'} name="category"/></label>}{tab === 'materials' ? <><label><span className="field-label">Composition</span><input className="field" name="composition" placeholder="Wool, linen, silk…"/></label><label><span className="field-label">Color name</span><input className="field" name="colorName" placeholder="Midnight indigo"/></label><label><span className="field-label">Color</span><input className="field h-12 p-1" defaultValue="#9A6C3C" name="colorHex" type="color"/></label></> : <div/>}<div className="xl:col-span-5"><Button type="submit" variant="primary">Add to the Studio</Button></div></form></Card>; }
function SecondaryPanel({ children, title }: { children: ReactNode; title: string }) { return <details className="rounded-[1.2rem] bg-stardust/[0.025] p-5"><summary className="cursor-pointer text-sm font-medium text-stardust/72">{title}</summary><div className="mt-4 border-t border-bronze/12 pt-4">{children}</div></details>; }
function SupplierDetails({ state, supplierItems }: { state: WorkspaceState; supplierItems: WorkspaceState['supplierItems'] }) { if (!supplierItems.length) return <p className="text-sm text-stardust/42">No supplier offers yet.</p>; return <div className="space-y-3">{supplierItems.map((item) => <div key={item.id}><p className="text-sm font-medium text-stardust/72">{state.suppliers.find((supplier) => supplier.id === item.supplierId)?.name ?? 'Supplier'}</p><p className="mt-1 text-xs text-stardust/42">{item.currency} {item.unitCost.toFixed(2)} · {item.leadTimeDays ?? '—'} day lead time</p></div>)}</div>; }
function TextileSwatch({ children, className = '', color }: { children?: ReactNode; className?: string; color: string | null }) { return <div className={`relative overflow-hidden rounded-[1.3rem] ring-1 ring-inset ring-stardust/8 ${className}`} style={{ background: swatchBackground(color) }}><div className="absolute inset-0 opacity-35 [background-image:repeating-linear-gradient(0deg,transparent,transparent_3px,rgba(255,255,255,.06)_4px),repeating-linear-gradient(90deg,transparent,transparent_5px,rgba(0,0,0,.14)_6px)]" />{children}</div>; }
function swatchBackground(color: string | null) { const safe = color && /^#[0-9a-f]{6}$/i.test(color) ? color : '#5e4b3b'; return `radial-gradient(circle at 25% 18%, rgba(255,255,255,.2), transparent 36%), linear-gradient(145deg, ${safe}, ${darkenHex(safe)})`; }
function darkenHex(color: string) { const channels = [1, 3, 5].map((index) => Math.round(Number.parseInt(color.slice(index, index + 2), 16) * 0.42).toString(16).padStart(2, '0')); return `#${channels.join('')}`; }
function garmentsUsingVariant(state: WorkspaceState, variantId: string) { const ids = new Set(state.garmentMaterials.filter((item) => item.variantId === variantId).map((item) => item.garmentId)); return state.garments.filter((garment) => ids.has(garment.id)); }
function materialPersonality(category: string, composition: string, weight: number | null) { const text = `${category} ${composition}`.toLowerCase(); if (text.includes('linen')) return { description: 'Airy, quietly textured, and relaxed without losing intention. It brings natural movement and a lived-in refinement to the silhouette.', title: 'Breathable and quietly structured' }; if (text.includes('denim') || (weight ?? 0) >= 300) return { description: 'Substantial, protective, and sculptural. This textile holds a decisive line while gathering character through wear and construction.', title: 'Architectural with a lived-in edge' }; if (text.includes('silk') || text.includes('satin')) return { description: 'Fluid and light-responsive, with a polished surface that turns movement into part of the garment’s story.', title: 'Fluid, luminous, and expressive' }; if (text.includes('knit')) return { description: 'Soft, adaptable, and close to the body. It gives the garment ease while preserving a considered surface and color presence.', title: 'Soft structure with natural movement' }; return { description: 'A versatile foundation with enough character to shape the silhouette, color story, and hand-feel of the finished garment.', title: 'Tactile, versatile, and considered' }; }
function MaterialEmpty() { return <div className="atelier-empty-state flex min-h-[25rem] flex-col items-center justify-center"><Sparkles aria-hidden="true" className="text-ember/58" size={34}/><h2 className="font-display mt-5 text-3xl">Begin the textile archive</h2><p className="mt-3 max-w-lg text-sm leading-6 text-stardust/50">Add fabrics by name, composition, and color. Their garment use, suppliers, and inventory will gather naturally around them.</p></div>; }
function Empty({ tab }: { tab: VaultTab }) { return <div className="p-5 text-center"><Archive aria-hidden="true" className="mx-auto text-stardust/40"/><p className="mt-3 text-sm text-stardust/60">No {tab} match this view.</p></div>; }
function Tab({ active, label, onClick }: { active: boolean; label: string; onClick: () => void }) { return <button aria-pressed={active} className={active ? 'min-h-11 shrink-0 rounded-xl bg-ember px-4 text-sm font-medium text-midnight' : 'min-h-11 shrink-0 rounded-xl px-4 text-sm text-stardust/58 hover:bg-stardust/[0.05]'} onClick={onClick} type="button">{label}</button>; }
function Pill({ children }: { children: ReactNode }) { return <span className="rounded-full bg-stardust/[0.05] px-3 py-2 text-xs text-stardust/62">{children}</span>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs uppercase tracking-[0.12em] text-stardust/38">{label}</dt><dd className="mt-1 text-sm text-stardust/76">{value}</dd></div>; }
